### ISSUE TITLE
Why do not you use bert or prompt-bert to train instead of using t5?

### ISSUE THREAD

**Issue by YWMditto** [MatthewCYM/GenSE#3]
Hello! Congratulations for this great work!

I want to ask that why don't you just use bert or prompt-bert directly after deriving these augmented data.
Does use t5 or other generation models work better than bert which is nlu model?

Cause I have used t5 and bart directly to run simcse training, but the results are just like a piece of shit......

**Comment by MatthewCYM** [comment]
Hi @YWMditto ,

Thank you for your interest in our work!

We initialize all our models (data synthesizer, sentence embedding) from the same T5 checkpoint for modeling simplicity.

About T5 directly trained with simcse, it should give competitive results (STS avg. 82.81), as reported in [ST5](https://arxiv.org/pdf/2108.08877.pdf) paper. Our implementation also give similar results.

I suggest that you can double check your implementation. Maybe there's some bugs inside.

**Comment by YWMditto** [comment]
Thanks for your reply！
And here are my further thinking:
1. Did you try to use the augmented data on bert or promptbert？I just want to check that whether it is better to use generation models or nlu models.
2. I want to verify this question: the sentence embedding model to be trained does not share its parameters with the data synthesizer model, but they are both initialized from the same T5 checkpoint, am I right?

Thanks again for your answers!!!

**Comment by MatthewCYM** [comment]
Hi @YWMditto,

Q1. We didn't train encoder-based models with our synthetic data.

Q2. Yes, they are initialized from the same checkpoint without parameter sharing.

**Comment by YWMditto** [comment]
Ok, that makes sense, thanks a lot for your patient reply, best wishes!
