### ISSUE TITLE
Release Synthetic Corpus

### ISSUE THREAD

**Issue by Jiahao004** [MatthewCYM/GenSE#4]
Hi Yiming, great work for synthetic corpus generation on STS task! I have a simple request, will you be able to release the generated synthetic corpus? Many thanks for your contribution!

**Comment by MatthewCYM** [comment]
Hi Jiahao,

Thank you for you interest in our work.

We have already released the synthetic corpus. You may load it from huggingface hub:
```
from datasets import load_dataset

dataset = load_dataset("mattymchen/synli")
```

**Comment by Jiahao004** [comment]
Thank you so much !
