### ISSUE TITLE
How to train generator and discriminator

### ISSUE THREAD

**Issue by qmin2** [MatthewCYM/GenSE#5]
Dear author, 

I've been reading your paper and I have a question regarding the training process for the generator and discriminator. 
I understand that C4 news-like and English partitions are used to obtain synthetic triplets.
but I'm still confused about how the generator and discriminator models are trained without labeled data.
(I feel like the input-output pairs data are needed to train the generator and discriminator model, but the datas above are only just a sampled sentence)

Could you please clarify this for me? 

 Thank you

**Comment by MatthewCYM** [comment]
Hi @qmin2 ,

Sorry for the late reply. Following previous works, e.g., SimCSE, SBERT, we use the supervised NLI (SNLI+MNLI) data to train our generator and discriminator model.
